include:
- file: /r4.1/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.1/gitlab-dom0.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
- file: /r4.2/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration

checks:shellcheck:
  stage: checks
  tags:
    - docker
  script:
    - shellcheck bin/yk-auth
